### ISSUE TITLE
"tx not possible" ?

### ISSUE THREAD

**Issue by sebseb7** [graft-project/GraftNetwork#69]
Wallet has enough unlocked balance. What is the problem here?

{"code":-4,"message":"tx not possible"}
2018-01-17 16:02:14 [payments] Payments failed to send to {"amount":15100000000,"address":"GA.....................................N"} { amount: 14800000000,
  address: 'G6k..........................m' } { amount: 81800000000,
  address: 'G6J.......................Z' }

wallet-rpc-daemon says:

4588 2018-01-17 15:02:14.607 [RPC0]  ERROR   wallet.wallet2  src/wallet/wallet2.cpp:4510 1. THROW EXCEPTION: error::tx_not_possible
4589 2018-01-17 15:02:14.607 [RPC0]  WARN    net.http    src/wallet/wallet_errors.h:707  /opt/GraftNetwork/src/wallet/wallet2.cpp:4510:N5tools5error15tx_not_possibleE: tx not possible, available = 201.8605011040, tx_amount = 11.1700000000, fee = 0.1997206120
4590 2018-01-17 15:02:14.607 [RPC0]  INFO    stacktrace  src/common/stack_trace.cpp:120  Exception: tools::error::tx_not_possible
4591 2018-01-17 15:02:14.607 [RPC0]  INFO    stacktrace  src/common/stack_trace.cpp:121  Unwound call stack:
4592 2018-01-17 15:02:14.609 [RPC0]  INFO    stacktrace  src/common/stack_trace.cpp:159      [1] ./graft-wallet-rpc:__cxa_throw+0xfe [0x55f4f101814e]

**Comment by mbg033** [comment]
Hi, please update to the latest master, should be fixed now

**Comment by bobbieltd** [comment]
I use recent code (4 days ago) and I still have this issue too. Please recheck,

**Comment by mbg033** [comment]
@bobbieltd we never faced with such issue with recent code. If you still having it, please email me detailed wallet log (--log-level=3)

**Comment by bobbieltd** [comment]
Thanks. It happened only once and never happens again. So it’s OK.

**Comment by paullovesjenn2020** [comment]
I am also having this issue on my graft wallet on my windows pc as well as my wallet on my mobile and I have over 40000 coins in one and little over 50000 coins in the other my email is Dontblinkorullmissme@gmail.com if anyone could help me
